apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: sentry-enterprise
spec:
  title: Ericsson 5G Dispatch
  icon: https://static-00.iconduck.com/assets.00/ericsson-icon-419x512-fidcuyvt.png
  statusInformers:
    - service/sentry
    - deployment/sentry-web
    - deployment/sentry-worker
  ports:
    - serviceName: "sentry"
      servicePort: 9000
      localPort: 9000
      applicationUrl: "http://sentry"
  releaseNotes: |
    Version 9.1.1
    -------------

    - Bug fixes from 9.1.0 release.

    Version 9.1
    -----------

    The changelog for Sentry 9.1 is summarized. For full details, we recommend reviewing the
    full set of SCM changes on GitHub.

    First, an important preface:

    FUTURE VERSIONS OF SENTRY WILL INTRODUCE BACKWARDS INCOMPATIBLE INFRASTRUCTURE

    This is the last version in the 9.x series, and our next release will migrate many legacy technologies onto standardized versions our SaaS service uses. The most notable, known concerns are:

    - Postgres will be the only supported SQL database
    - Our new search infrastructure (codenamed Snuba) will become required (we'll provide a migration path)
    - Various new infrastructure services will be required (such as Kafka)

    This is required for Sentry to continue to support open source releases in a meaningful way, and ensures we have only a single, standard way of running the services.

    Integrations
    ~~~~~~~~~~~~

    We've added a new global integration concept to Sentry, which raises plugins to the organization level. Access to these integrations are controlled with the `org:integrations` scope, and are granted to any user with an Admin or higher role.

    This release includes integrations for:

    - Azure DevOps
    - BitBucket
    - GitHub
    - GitHub Enterprise
    - GitLab
    - Jira
    - Jira Server

    There is additionally a Slack integration, though it requires a now-deprecated workspace token in order to use.

    Note: a known issue exists where integrations are always shown as enabled, even when you haven't configured the appropriate server settings (such as OAuth keys).

    Native Support
    ~~~~~~~~~~~~~~

    Various improvements for native (compiled) runtimes is included in this release.

    - Improved rendering for native stacktraces.
    - Improved support for Apple crash reports.
    - Added unreal engine 4 crash dump support.
    - Added code identifier support for debug files.

    Security
    ~~~~~~~~

    - Added SAML2 SSO support.
    - Member invitations will now automatically expire after 30 days.
    - Fixed potential settings exposure if sentry was deployed in DEBUG mode.

    Misc
    ~~~~

    - Settings have been greatly improved and updated to allow non-admins read-only access in many areas.
    - Added additional localization configuration for User Feedback dialogs.
    - Added account session history under Account Settings -> Security -> Session History.
    - Event data stored in Redis & RabbitMQ no longer uses pickle to encode data. All data is now encoded in JSON.
    - Various improvements to CSP and other browser Reporting API support.
    - Many features disabled via feature flags now indicate how to enable them in the UI.
    - Improved suspect commit generation for Java projects.
    - Repository access is now coupled to integrations access (`org:integrations`)
    - Various improvements to exception fingerprinting.

    Version 9.0
    -----------

    The changelog for Sentry 9 is summarized. For full details, we recommend reviewing the
    full set of SCM changes on GitHub. There are far too many changes to list in Sentry 9,
    but the major highlights are documented below.

    There are also significant schema and data changes in this release, so plan for a huge amount
    of updates and a measurable increase in utilization of your data stores.

    Note: Major features which are undocumented here should be considered unstable, and are almost
    certainly behind a feature switch which is intended to be disabled.

    Dashboard
    ~~~~~~~~~

    We've removed the project-manager-esque dashboard and brought back a team/card based selection as
    as a new sidebar for quick access. We will continue to iterate on what projects mean in Sentry
    going forward and this is simply a first step towards future changes.

    Settings
    ~~~~~~~~

    A new global settings UI has been introduced. This is an attempt to unify all settings and make
    it easier to find the numerous configuration options throughout Sentry.

    Environments
    ~~~~~~~~~~~~

    Environments have been moved up in the hierarchy and are now a first class citizen. While
    still early, this is intended to replace the need for having separate projects per environment.

    To use environments you simply need to ensure you're configuring the ``environment`` parameter
    in the Sentry SDK, and it should automatically propagate into Sentry proper.

    Owners
    ~~~~~~

    A new owners feature allows you to define per-project rules for declaring explicit ownership.
    Much like GitHub's .gitowners, this helps Sentry understand who is responsible for a specific
    issue, and more importantly lets you limit email alerts to only the relevant parties.

    In addition to explicit owners, the release framework has expanded to support implicit owners
    and suspect commits. This currently only works with GitHub.com hosted repositories, but will be
    expanded to support other providers in future versions of Sentry.

    Teams & Projects
    ~~~~~~~~~~~~~~~~

    Projects can now be associated with many teams, and teams can be referenced in comments and
    assignment as well as the new ownership features.

    Both Team and Project names have been deprecated, and the short name as been promoted as the
    canonical reference. Teams can be mentioned using #team-name.

    Integrations
    ~~~~~~~~~~~~

    The beginnings of the new integration framework (plugin v3) have landed, along with an initial
    version of a new Slack integration.

    The new integrations framework will likely change in upcoming versions of Sentry, and we dont
    suggest building against it yet.

    Some caveats:

    - The Slack integration requires Slack workspace tokens.
    - While there is some early work of other integrations in this release, they are not yet GA nor
      are they exposed.

    API
    ~~~

    Various portions of processing for the API will require additional dependencies and configuration
    (such as symbolic).

    - The 'secret key' for a DSN is no longer required and has been deprecated in SDKs.
    - Added support for Minidumps generated by Breakpad and Crashpad.
    - Added support for Cordova and Electron.
    - A new standard 'security report' endpoint has been exposed, which supports HKPK, CSP,
      Expect-CT, and Expect-Staple reports.
    - Improved reprocessing feature.
    - Improved support for native Debug Symbols (Apple, Linux).
    - The ingestion API is now JSON-schema based (though still fairly flexible).
    - Added setup wizard for various SDKs (e.g. react-native).

    Privacy Changes
    ~~~~~~~~~~~~~~~

    As part of GDPR, the open source version of Sentry now changes the default policy for its beacon
    (the service which tells sentry.io statistics about open source usage) to **not** send the system's
    contact email address by default. You can still opt-in to this, which will allow us to contact you
    in the event of a major security issue.

    Misc
    ~~~~

    - User Feedback will now send an email notification.
    - Almost all major UI components are now driven by the client-side application.
    - Avatars have been added for organizations.
    - Various improvements to issue hashing, specifically for native (iOS) and javascript
      applications.
    - Various improvements to Single Sign-On flows. You should update any external auth extensions
      you're using as part of this (sentry-auth-github, sentry-auth-google).
    - Support for SAML via sentry-auth-saml2.
    - Support for Google Cloud Storage as a storage backend.
    - A new Assistant to help onboard users.
    - Add count estimates to search results.
    - Superuser has been locked down significantlly with idle timeouts and secondary sessions.
    - 2FA can now be enforced for an organization.
    - Various performance around event processing to make up for all the added load we're forcing on
      ya'll. =)

